In [29]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
from Twitter_bot_detection_713.data_prep import tweet_df_cleaner, user_df_cleaner,get_final_tweet_data

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
tweet_df = pd.read_parquet('data/tweets_df.parquet')
user_df = pd.read_csv('../raw_data/users_data.csv', sep='\t', lineterminator='\n')

In [ ]:
def get_final_tweet_data(en=False):
    tweet_df = pd.read_parquet('..data/tweets_df.parquet')
    user_df = pd.read_csv('../raw_data/users_data.csv', sep='\t', lineterminator='\n')
    t_df = tweet_df_cleaner(tweet_df)
    u_df = user_df_cleaner(user_df)
    target_join = u_df[['author_id', 'target']]
    t_joined = t_df.merge(target_join, on='author_id', how='left')
    if en == True:
        t_joined = t_joined[t_joined['lang'] == 'en']
    return t_joined

In [7]:
print(tweet_df.shape)
print(user_df.shape)

(2353375, 12)
(36234, 15)

In [8]:
tweet_df.head()

,possibly_sensitive,lang,attachments,author_id,id,text,public_metrics,created_at,entities,in_reply_to_user_id,referenced_tweets,withheld
0,False,en,"{'media_keys': ['3_1463160440935047191'], 'pol...",787405734442958848,1463160444609351697,"Let's be the ""Ill""\nin ""Fillet"" https://t.co/l...","{'like_count': 3, 'quote_count': 0, 'reply_cou...",2021-11-23T15:00:08.000Z,None,None,None,None
1,False,en,"{'media_keys': ['3_1463115131844390914'], 'pol...",787405734442958848,1463115136424546310,"You can't spell\n""Ambitious""\nwithout ""Bit"" ht...","{'like_count': 0, 'quote_count': 0, 'reply_cou...",2021-11-23T12:00:06.000Z,None,None,None,None
2,False,en,"{'media_keys': ['3_1463069825182285824'], 'pol...",787405734442958848,1463069828768403458,"We can put the\n""Cable"" back in\n""Inexplicable...","{'like_count': 2, 'quote_count': 0, 'reply_cou...",2021-11-23T09:00:04.000Z,None,None,None,None
3,False,en,"{'media_keys': ['3_1463024540825518082'], 'pol...",787405734442958848,1463024544902307840,"We can't spell\n""Brute"" without ""Rut"" https://...","{'like_count': 0, 'quote_count': 0, 'reply_cou...",2021-11-23T06:00:07.000Z,None,None,None,None
4,False,en,"{'media_keys': ['3_1462979239485927428'], 'pol...",787405734442958848,1462979242451365892,"We need ""Abet""\nto spell ""Diabetes"" https://t....","{'like_count': 2, 'quote_count': 0, 'reply_cou...",2021-11-23T03:00:06.000Z,None,None,None,None

In [9]:
user_df.head()

,Unnamed: 0,id,username,name,description,location,created_at,verified,protected,profile_image_url,followers_count,following_count,tweet_count,listed_count,account_type
0,0,787405734442958848,best_in_dumbest,The Best In Dumbest,"Blame @xaiax, Inspired by @MakingInvisible, us...",NaN,2016-10-15T21:32:11.000Z,False,False,https://pbs.twimg.com/profile_images/787412182...,1848,5,14542,0,bot
1,1,796216118331310080,CJRubinPhoto,CJ Rubin,Photographing the American West since 1980. I ...,Estados Unidos,2016-11-09T05:01:30.000Z,False,False,https://pbs.twimg.com/profile_images/802329632...,812,845,251,5,human
2,2,875949740503859204,SVGEGENT,🔥𝖙𝖍𝖊 𝖘𝖆𝖛𝖆𝖌𝖊 𝖌𝖊𝖓𝖙𝖑𝖊𝖒𝖆𝖓🔥,Part savage all gentleman ...,NaN,2017-06-17T05:34:27.000Z,False,False,https://pbs.twimg.com/profile_images/146262520...,182,885,1288,2,human
3,3,756119643622735875,TinkerVHECHK5,Danielle Tinker,Wife.Godmother.Friend.Feline Fanatic! Principa...,"Birmingham, AL",2016-07-21T13:32:25.000Z,False,False,https://pbs.twimg.com/profile_images/128488492...,657,747,1920,2,human
4,4,464781334,JoleonLescott,Joleon Lescott,England U21 Assistant Coach | @pumafootball Am...,"England, United Kingdom",2012-01-15T16:32:35.000Z,True,False,https://pbs.twimg.com/profile_images/143779909...,739915,120,4459,1800,human

In [10]:
t_df = tweet_df_cleaner(tweet_df)
u_df = user_df_cleaner(user_df)

In [12]:
t_df

,author_id,id,lang,text,created_at,lag,possibly_sensitive,referenced_tweets,reply_category,like_count,quote_count,reply_count,retweet_count,n_mentions
0,1000029438233448448,1006523283645370368,it,@luisellacost Li facciamo venire tutti a casa ...,2018-06-12 13:07:05+00:00,NaT,False,True,Reply_to_other,1,0,0,0,1
1,1000029438233448448,1006561127600451595,it,"@matteosalvinimi Siamo sulla strada giusta, ad...",2018-06-12 15:37:28+00:00,0 days 02:30:23,False,True,Reply_to_other,0,0,0,0,1
2,1000029438233448448,1008732795357655040,it,@matteosalvinimi Auguroni,2018-06-18 15:26:54+00:00,5 days 23:49:26,False,True,Reply_to_other,4,0,1,0,1
3,1000029438233448448,1008984071031148544,it,@LegaSalvini Denunciate questo tizio per diffa...,2018-06-19 08:05:23+00:00,0 days 16:38:29,False,True,Reply_to_other,0,0,0,0,1
4,1000029438233448448,1009725886579593216,it,@Pontifex_it @M_RSezione Dopo wojtyla siete il...,2018-06-21 09:13:05+00:00,2 days 01:07:42,False,True,Reply_to_other,0,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2353370,999977095106367488,1433726665553743872,it,"@stiIIxgolden madonna quanto ti posso capire, ...",2021-09-03 09:40:49+00:00,4 days 21:37:39,False,True,Reply_to_other,0,0,1,0,1
2353371,999977095106367488,1435588625811611648,en,song i wish someone wrote for me pt2: https://...,2021-09-08 12:59:34+00:00,5 days 03:18:45,False,False,No_reply,0,0,0,0,0
2353372,999977095106367488,1436375696033697835,en,Behavioral research is built into every journe...,2021-09-10 17:07:07+00:00,2 days 04:07:33,False,False,No_reply,0,0,0,0,0
2353373,999977095106367488,1445091030156648450,it,"@tisaniina sì, sad",2021-10-04 18:18:44+00:00,24 days 01:11:37,False,True,Reply_to_other,1,0,0,0,1
2353374,999977095106367488,1446584167379111937,und,&lt;3 u https://t.co/YpDV9SKeEA,2021-10-08 21:11:56+00:00,4 days 02:53:12,False,False,No_reply,1,0,0,0,0

In [13]:
u_df

,author_id,username,user_display_name,user_desc,user_created_at,user_verified,user_private,user_followers_cnt,user_following_cnt,user_tweet_count,user_list_count,target
0,787405734442958848,best_in_dumbest,The Best In Dumbest,"Blame @xaiax, Inspired by @MakingInvisible, us...",2016-10-15 21:32:11+00:00,False,False,1848,5,14542,0,bot
1,796216118331310080,CJRubinPhoto,CJ Rubin,Photographing the American West since 1980. I ...,2016-11-09 05:01:30+00:00,False,False,812,845,251,5,human
2,875949740503859204,SVGEGENT,🔥𝖙𝖍𝖊 𝖘𝖆𝖛𝖆𝖌𝖊 𝖌𝖊𝖓𝖙𝖑𝖊𝖒𝖆𝖓🔥,Part savage all gentleman ...,2017-06-17 05:34:27+00:00,False,False,182,885,1288,2,human
3,756119643622735875,TinkerVHECHK5,Danielle Tinker,Wife.Godmother.Friend.Feline Fanatic! Principa...,2016-07-21 13:32:25+00:00,False,False,657,747,1920,2,human
4,464781334,JoleonLescott,Joleon Lescott,England U21 Assistant Coach | @pumafootball Am...,2012-01-15 16:32:35+00:00,True,False,739915,120,4459,1800,human
...,...,...,...,...,...,...,...,...,...,...,...,...
36229,63963107,butchsekab,Rosemary Pearman nee Bakes,"Unemployed! Retail Assistant, Stocktaker, Dry ...",2009-08-08 13:11:15+00:00,False,False,152,1219,487,3,human
36230,1064042478,Mathieu_Era,Tyrann Mathieu,FOLLOW ME ON IG.,2013-01-05 21:35:37+00:00,True,False,1237990,799,27326,1475,human
36231,1089732602,SDalmaoficial,Sergio Dalma,Bienvenid@s al Twitter Oficial de Sergio Dalma...,2013-01-14 18:05:54+00:00,True,False,85615,189,6640,270,human
36232,815529979,VinceYearly,Mr. Vance,Just a good guy wrapped up in a bad system.\nA...,2012-09-10 16:12:02+00:00,False,False,137,166,1040,3,human
36233,434896892,zhemcom,zhemcom,你好！中国,2011-12-12 12:59:28+00:00,False,False,3,0,1521,0,bot

In [14]:
target_join = u_df[['author_id', 'target']]
target_join

                author_id target
0      787405734442958848    bot
1      796216118331310080  human
2      875949740503859204  human
3      756119643622735875  human
4               464781334  human
...                   ...    ...
36229            63963107  human
36230          1064042478  human
36231          1089732602  human
36232           815529979  human
36233           434896892    bot

[36234 rows x 2 columns]

In [15]:
t_joined = t_df.merge(target_join, on='author_id', how='left')

In [18]:
t_joined['target'].value_counts()/len(t_joined)

human    0.840141
bot      0.159859
Name: target, dtype: float64

In [20]:
en_tweets = t_joined[t_joined['lang'] == 'en']

In [24]:
en_tweets['author_id'].value_counts()

human    1395617
bot       217363
Name: target, dtype: int64

In [22]:
u_df

,author_id,username,user_display_name,user_desc,user_created_at,user_verified,user_private,user_followers_cnt,user_following_cnt,user_tweet_count,user_list_count,target
0,787405734442958848,best_in_dumbest,The Best In Dumbest,"Blame @xaiax, Inspired by @MakingInvisible, us...",2016-10-15 21:32:11+00:00,False,False,1848,5,14542,0,bot
1,796216118331310080,CJRubinPhoto,CJ Rubin,Photographing the American West since 1980. I ...,2016-11-09 05:01:30+00:00,False,False,812,845,251,5,human
2,875949740503859204,SVGEGENT,🔥𝖙𝖍𝖊 𝖘𝖆𝖛𝖆𝖌𝖊 𝖌𝖊𝖓𝖙𝖑𝖊𝖒𝖆𝖓🔥,Part savage all gentleman ...,2017-06-17 05:34:27+00:00,False,False,182,885,1288,2,human
3,756119643622735875,TinkerVHECHK5,Danielle Tinker,Wife.Godmother.Friend.Feline Fanatic! Principa...,2016-07-21 13:32:25+00:00,False,False,657,747,1920,2,human
4,464781334,JoleonLescott,Joleon Lescott,England U21 Assistant Coach | @pumafootball Am...,2012-01-15 16:32:35+00:00,True,False,739915,120,4459,1800,human
...,...,...,...,...,...,...,...,...,...,...,...,...
36229,63963107,butchsekab,Rosemary Pearman nee Bakes,"Unemployed! Retail Assistant, Stocktaker, Dry ...",2009-08-08 13:11:15+00:00,False,False,152,1219,487,3,human
36230,1064042478,Mathieu_Era,Tyrann Mathieu,FOLLOW ME ON IG.,2013-01-05 21:35:37+00:00,True,False,1237990,799,27326,1475,human
36231,1089732602,SDalmaoficial,Sergio Dalma,Bienvenid@s al Twitter Oficial de Sergio Dalma...,2013-01-14 18:05:54+00:00,True,False,85615,189,6640,270,human
36232,815529979,VinceYearly,Mr. Vance,Just a good guy wrapped up in a bad system.\nA...,2012-09-10 16:12:02+00:00,False,False,137,166,1040,3,human
36233,434896892,zhemcom,zhemcom,你好！中国,2011-12-12 12:59:28+00:00,False,False,3,0,1521,0,bot

In [26]:
en_tweets[en_tweets['target']=='bot']

,author_id,id,lang,text,created_at,lag,possibly_sensitive,referenced_tweets,reply_category,like_count,quote_count,reply_count,retweet_count,n_mentions,target
1116,1001667553,953924017861230593,en,"hey man, all this can be your. Just see site i...",2018-01-18 09:36:23+00:00,NaT,False,False,No_reply,0,0,0,0,0,bot
1118,1001667553,971774363795165184,en,Hello! What are you doing? I'm sad ... Look to...,2018-03-08 15:47:17+00:00,49 days 06:08:22,False,False,No_reply,0,0,0,0,0,bot
1119,1001667553,971774542128599040,en,Love is a fire. But whether it is going to war...,2018-03-08 15:48:00+00:00,0 days 00:00:43,False,False,No_reply,0,0,0,0,0,bot
1122,1001667553,971889284805484544,en,Hello! How are you? My new photo shoot in bio!...,2018-03-08 23:23:56+00:00,0 days 07:33:56,False,False,No_reply,0,0,0,0,0,bot
1124,1001667553,972287385047388161,en,We are never so defensless against suffering a...,2018-03-10 01:45:51+00:00,1 days 02:21:03,False,False,No_reply,0,0,0,0,0,bot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2352722,99943864,1463070074126811137,en,https://t.co/rUtxZozrRA\n\nChicago Bears vs. D...,2021-11-23 09:01:02+00:00,0 days 00:03:38,False,False,No_reply,0,0,1,0,0,bot
2352738,99943864,1463198540625330177,en,@lpyr56 @nytimes Spoken like a true racist!,2021-11-23 17:31:31+00:00,0 days 08:27:02,False,True,Reply_to_other,0,0,0,0,2,bot
2352740,99943864,1463201848559603724,en,@thehill So thanks to #Democrats they'll now h...,2021-11-23 17:44:40+00:00,0 days 00:06:44,False,True,Reply_to_other,0,0,0,0,1,bot
2352773,99943864,1463233312344977411,en,@thehill Translation:\nPedo Joe squints and mu...,2021-11-23 19:49:41+00:00,0 days 00:51:31,False,True,Reply_to_other,1,0,0,0,1,bot
2352774,99943864,1463235260230078464,en,@FoxNews Is anyone honestly surprised? #Democr...,2021-11-23 19:57:26+00:00,0 days 00:07:45,False,True,Reply_to_other,2,0,1,1,1,bot

In [31]:
get_final_tweet_data(en=True)

,author_id,id,lang,text,created_at,lag,possibly_sensitive,referenced_tweets,reply_category,like_count,quote_count,reply_count,retweet_count,n_mentions,target
13,1000197919,1261733558474829824,en,@trekonomics Same here. Best pate ever....have...,2020-05-16 19:01:36+00:00,33 days 14:13:11,False,True,Reply_to_other,0,0,0,0,1,human
14,1000197919,1264695397588406272,en,PCC is a great example....reach out to your el...,2020-05-24 23:10:54+00:00,8 days 04:09:18,False,True,No_reply,0,0,0,0,0,human
15,1000197919,1271119064941752320,en,both the theorem - and the conclusion. https:/...,2020-06-11 16:36:15+00:00,17 days 17:25:21,False,True,No_reply,0,0,0,0,0,human
16,1000197919,1273846820133695488,en,@GeneralCattis they're learning from the best!,2020-06-19 05:15:23+00:00,7 days 12:39:08,False,True,Reply_to_other,0,0,0,0,1,human
17,1000197919,1275472007769976832,en,this thread... https://t.co/OSveBlPctt,2020-06-23 16:53:18+00:00,4 days 11:37:55,False,True,No_reply,0,0,0,0,0,human
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2353366,999977095106367488,1426676881638793216,en,you ruined everything good\nalways said you we...,2021-08-14 22:47:29+00:00,0 days 13:31:13,False,False,No_reply,0,0,0,0,0,human
2353367,999977095106367488,1427777414088777728,en,for every question why \nyou were my because,2021-08-17 23:40:36+00:00,3 days 00:53:07,False,False,No_reply,0,0,0,0,0,human
2353369,999977095106367488,1431950553173659648,en,song i wish someone wrote for me pt1: https://...,2021-08-29 12:03:10+00:00,8 days 15:31:58,False,False,No_reply,0,0,0,0,0,human
2353371,999977095106367488,1435588625811611648,en,song i wish someone wrote for me pt2: https://...,2021-09-08 12:59:34+00:00,5 days 03:18:45,False,False,No_reply,0,0,0,0,0,human
2353372,999977095106367488,1436375696033697835,en,Behavioral research is built into every journe...,2021-09-10 17:07:07+00:00,2 days 04:07:33,False,False,No_reply,0,0,0,0,0,human